artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://drive.google.com/uc?export=download&id=1LsRanNVunDLsGGnTSutTpkoKUoOLXZ5y
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion